<a href="https://colab.research.google.com/github/Ishita-01/Cognitive-Lab/blob/main/CC_Ass4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ques 1


In [6]:
import numpy as np
arr= np.array([2,4,6,8,10])
print("Addition: ",arr+2)
print("Multiplication: ",arr*3)
print("Division: ",arr/2)

Addition:  [ 4  6  8 10 12]
Multiplication:  [ 6 12 18 24 30]
Division:  [1. 2. 3. 4. 5.]


Ques 2


In [15]:
import numpy as np
arr=np.array([1,2,3,6,4,5])
print(f"Original array: {arr}")
#reverse
print(f"Reversed array: {arr[::-1]}")

#most frequent

def most_frequent_with_indices(arr):
    counts = np.bincount(arr)
    max_count = np.max(counts)
    most_frequent_values = np.where(counts == max_count)[0]
    indices_dict = {value: np.where(arr == value)[0] for value in most_frequent_values}
    return most_frequent_values, indices_dict

x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])
frequent_x,indices_x= most_frequent_with_indices(x)
frequent_y,indices_y= most_frequent_with_indices(y)
print(f"Most frequent in x: {frequent_x} at indice(s) {indices_x}")
print(f"Most frequent in y: {frequent_y} at indice(s) {indices_y}")

Original array: [1 2 3 6 4 5]
Reversed array: [5 4 6 3 2 1]
Most frequent in x: [1] at indice(s) {1: array([0, 5, 7, 8, 9])}
Most frequent in y: [1 3] at indice(s) {1: array([0, 1, 2]), 3: array([4, 8, 9])}


Ques 3

In [2]:
import numpy as np
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr[0][1])
print(arr[2][0])

20
70


Ques 4

In [8]:
import numpy as np
Your_Name=np.linspace(10,100,25)
print(Your_Name)
print("The dimensions of array: ",Your_Name.ndim)
print("Shape: ",Your_Name.shape)
print("Total elements: ",Your_Name.size)
print("Data type of each element: ",Your_Name.dtype)
print("Total number of bytes: ",Your_Name.nbytes)

Transpose_re=Your_Name.reshape(25,1)
print("Using reshape, Transpose: ")
print(Transpose_re)

Transpose_T=Your_Name.T
print("Using T attribute, Transpose: ")
print(Transpose_T)

print("Conclusion: No we Can't use T attribute.")

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
The dimensions of array:  1
Shape:  (25,)
Total elements:  25
Data type of each element:  float64
Total number of bytes:  200
Using reshape, Transpose: 
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Using T attribute, Transpose: 
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Conclusion: No we Can't use T attribute.


Ques 5

In [12]:
import numpy as np
ucs420= np.array([[10,20,30,40],
                  [50,60,70,80],
                  [90,15,20,35]])
print(f"Orginal:\n{ucs420}")
print("mean: ",np.mean(ucs420))
print("median: ",np.median(ucs420))
print("max: ",np.max(ucs420))
print("min: ",np.min(ucs420))
print("unique elements: ",np.unique(ucs420))
reshaped_ucs420= ucs420.reshape(4,3)
print(f"Reshaped:\n{reshaped_ucs420}")
resized_ucs420 = np.resize(ucs420,(2,3))
print(f"Resized:\n{resized_ucs420}")

Orginal:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
mean:  43.333333333333336
median:  37.5
max:  90
min:  10
unique elements:  [10 15 20 30 35 40 50 60 70 80 90]
Reshaped:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized:
[[10 20 30]
 [40 50 60]]
